# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    # Create VM and name it pc1
  config.vm.define "pc1" do |pc1|
    pc1.vm.box = "ubuntu/trusty64"

    #private Network configuration
    pc1.vm.network "private_network", ip: "192.168.100.101"
    pc1.vm.provision "shell", run: "always", inline: "route del default"
    pc1.vm.provision "shell", run: "always", inline: "route add default gw 192.168.100.254"

    #Display message when the process is completed
    pc1.vm.provision "shell", inline: "echo PC1 deployed"
  end

end
