# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
    # Create VM and name it pc1
  config.vm.define "pc1" do |pc1|
    pc1.vm.box = "ubuntu/trusty64"

    #private Network configuration
    pc1.vm.network "private_network", ip: "192.168.100.101"
    pc1.vm.provision "shell", run: "always", inline: "route del default"
    pc1.vm.provision "shell", run: "always", inline: "route add default gw 192.168.100.254"

    #Display message when the process is completed
    pc1.vm.provision "shell", inline: "echo PC1 deployed"
  end
    # Create router and name it router1
  config.vm.define "roter1" do |router1|
    router1.vm.box = "ubuntu/trusty64"

    #private Network configuration
    router1.vm.network "private_network", ip: "192.168.100.254"
    router1.vm.network "private_network", ip: "192.168.200.254"
    router1.vm.provision "shell", run: "always", inline: "route del default"
    router1.vm.provision "shell", inline: "sudo sysctl -w net.ipv4.ip_forward=1"

    #Display message when the process is completed
    router1.vm.provision "shell", inline: "echo router1 deployed"

  end
    # Create VM and name it pc2
  config.vm.define "pc1" do |pc2|
    pc2.vm.box = "ubuntu/trusty64"

    #private Network configuration
    pc2.vm.network "private_network", ip: "192.168.200.201"
    pc2.vm.provision "shell", run: "always", inline: "route del default"
    pc2.vm.provision "shell", run: "always", inline: "route add default gw 192.168.200.254"

    #Display message when the process is completed
    pc1.vm.provision "shell", inline: "echo PC2 deployed"
  end

end
